### ISSUE TITLE
Uninstall removes all dependencies

### ISSUE THREAD

**Issue by rob-packer** [DESIGNfromWITHIN/blogit#5]
I've been using getResources and Tagger for a while and thought I would give blogit a try. I did not add any extra functionality so I decided to remove it. In the process it also removed getResources and Tagger, as well as the Blog resource that existed before installing blogit. As a result major parts of my site were no longer working. Thankfully I discovered that the blog page had only been marked as deleted and to not show in the resource tree - by looking in the db.

It would be helpful to check the install date of extras and resources during the uninstall process and not remove those that were in use prior to blogit.

That would certainly save some pain.

**Comment by DESIGNfromWITHIN** [comment]
@rob-packer Thank, that is a great suggestion! Added to 1.1.0.

**Comment by Boddlnagg** [comment]
It would probably make a lot more sense to use the new "package dependencies" feature in MODX 2.4 for this: https://rtfm.modx.com/revolution/2.x/developing-in-modx/advanced-development/package-management/package-dependencies

**Comment by DESIGNfromWITHIN** [comment]
@Boddlnagg 
BlogIt 1.1.0-pl now supports package dependencies
(you need MODX 2.4.0-pl or up)
